services:
  nats:
    image: nats:latest
    restart: always
    command: --js
    ports:
      - "4222:4222"
    hostname:
      nats
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  manager:
    image: smoothsail/manager:latest
    depends_on:
      - db
      - nats
    volumes:
      - ./logs:/app/logs
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - SDKKEYSDB=postgres
      - NATS_SERVER=nats://nats:4222
      - LOGLEVEL=info
