services:
  nats:
    image: nats:latest
    restart: always
    command: --js
    ports:
      - "${NATS_PORT}:${NATS_PORT}"
    hostname:
      nats
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  manager:
    image: smoothsail/manager:latest
    depends_on:
      - db
      - nats
    volumes:
      - ./logs:/app/logs
    ports:
      - "${PORT}:${PORT}"
    environment:
      - SECRET_KEY
      - PORT
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - SDKKEYSDB=postgres
      - NATS_SERVER=nats://nats:${NATS_PORT}
      - LOGLEVEL=info
  sdk-service:
    image: smoothsail/sdk-service:latest
    depends_on:
      - nats
      - manager
      - db
    volumes:
      - ./logs:/app/logs
    ports:
      - "${SDK_SERVICE_PORT}:${SDK_SERVICE_PORT}"
    environment:
      - RATE_LIMIT
      - PORT=${SDK_SERVICE_PORT}
      - NATS_SERVER=nats://nats:${NATS_PORT}
      - LOGLEVEL=info
